Este script esta hecho para introducir todos los datasets train y test de los distintos archivos, es un repositorio a partir del cual otros scripts puedan extraer directamente la informacion y no sea necesario copiar todo el pifostio

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

TRAIN

In [2]:
df_train_1 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD001.txt', sep=" ", header=None)
df_train_2 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD002.txt', sep=" ", header=None)
df_train_3 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD003.txt', sep=" ", header=None)
df_train_4 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD004.txt', sep=" ", header=None)

In [3]:
list_df = [df_train_1, df_train_2, df_train_3, df_train_4]

In [4]:
list_units_1 = 3
operational_list = []
for n in range(1,list_units_1+1):
    operational = "operarional_setting_" + str(n)
    operational_list.append(operational)

list_units_2 = 23
sensor_measurement_list = []
for n in range(1,list_units_2+1):
    sensor = "sensor_measurement_" + str(n)
    sensor_measurement_list.append(sensor)

In [5]:
new_list = []
for df in list_df:
    
    df.columns = ["ID", "Cycle"] + operational_list + sensor_measurement_list

    df = df.dropna(axis=1)

    max_cycle_dataset_1 = df.groupby(["ID"])["Cycle"].max().reset_index()
    max_cycle_dataset_1 = max_cycle_dataset_1.rename(columns={"Cycle":"Max_cycle"})
    df = df.merge(max_cycle_dataset_1, how="inner", on="ID")
    df["RUL"] = df["Max_cycle"] - df["Cycle"]
    df = df.drop(["Max_cycle"],axis=1)

    df.drop(columns="operarional_setting_3",axis=1, inplace=True)
    columns_to_delete = ['sensor_measurement_1', 'sensor_measurement_5', 'sensor_measurement_6', 'sensor_measurement_10',"sensor_measurement_14", 'sensor_measurement_16', 'sensor_measurement_18', 'sensor_measurement_19']
    df.drop(columns=columns_to_delete, axis=1, inplace=True)
    new_list.append(df)

In [6]:
df_train_1 = new_list[0]
df_train_2 = new_list[1]
df_train_3 = new_list[2]
df_train_4 = new_list[3]

In [7]:
df_train_4

,ID,Cycle,operarional_setting_1,operarional_setting_2,sensor_measurement_2,sensor_measurement_3,sensor_measurement_4,sensor_measurement_7,sensor_measurement_8,sensor_measurement_9,sensor_measurement_11,sensor_measurement_12,sensor_measurement_13,sensor_measurement_15,sensor_measurement_17,sensor_measurement_20,sensor_measurement_21,RUL
0,1,1,42.0049,0.8400,549.68,1343.43,1112.93,137.36,2211.86,8311.32,41.69,129.78,2387.99,9.3335,330,10.62,6.3670,320
1,1,2,20.0020,0.7002,606.07,1477.61,1237.50,332.10,2323.66,8713.60,43.94,312.59,2387.73,9.1913,361,24.37,14.6552,319
2,1,3,42.0038,0.8409,548.95,1343.12,1117.05,138.18,2211.92,8306.69,41.66,129.62,2387.97,9.4007,329,10.48,6.4213,318
3,1,4,42.0000,0.8400,548.70,1341.24,1118.03,137.98,2211.88,8312.35,41.68,129.80,2388.02,9.3369,328,10.54,6.4176,317
4,1,5,25.0063,0.6207,536.10,1255.23,1033.59,174.82,1915.22,7994.94,36.48,164.11,2028.08,10.8366,305,14.03,8.6754,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61244,249,251,9.9998,0.2500,605.33,1516.36,1315.28,404.59,2319.66,8840.16,46.08,380.16,2388.73,8.4541,372,29.11,17.5234,4
61245,249,252,0.0028,0.0015,643.42,1598.92,1426.77,567.59,2388.47,9117.12,48.04,535.02,2388.46,8.2221,396,39.38,23.7151,3
61246,249,253,0.0029,0.0000,643.68,1607.72,1430.56,569.04,2388.51,9126.53,48.24,535.41,2388.48,8.2525,395,39.78,23.8270,2
61247,249,254,35.0046,0.8400,555.77,1381.29,1148.18,199.93,2223.78,8403.64,42.53,187.92,2388.83,9.0515,337,15.26,9.0774,1
61248,249,255,42.0030,0.8400,549.85,1369.75,1147.45,142.47,2212.52,8391.31,42.60,134.32,2388.66,9.1207,333,10.66,6.4341,0

TEST

In [8]:
df_test_1 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD001.txt', sep=" ", header=None)
df_test_2 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD002.txt', sep=" ", header=None)
df_test_3 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD003.txt', sep=" ", header=None)
df_test_4 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD004.txt', sep=" ", header=None)

In [9]:
list_df_test = [df_test_1, df_test_2, df_test_3, df_test_4]

In [10]:
new_list_test = []
for df in list_df_test:
    
    df.columns = ["ID", "Cycle"] + operational_list + sensor_measurement_list
    df = df.dropna(axis=1)

    df.drop(columns="operarional_setting_3",axis=1, inplace=True)
    columns_to_delete = ['sensor_measurement_1', 'sensor_measurement_5', 'sensor_measurement_6', 'sensor_measurement_10',"sensor_measurement_14", 'sensor_measurement_16', 'sensor_measurement_18', 'sensor_measurement_19']
    df.drop(columns=columns_to_delete, axis=1, inplace=True)
    new_list_test.append(df)

/home/dsc/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/home/dsc/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/home/dsc/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(
/home/dsc/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [11]:
df_test_1 = new_list_test[0]
df_test_2 = new_list_test[1]
df_test_3 = new_list_test[2]
df_test_4 = new_list_test[3]

In [12]:
df_test_4

,ID,Cycle,operarional_setting_1,operarional_setting_2,sensor_measurement_2,sensor_measurement_3,sensor_measurement_4,sensor_measurement_7,sensor_measurement_8,sensor_measurement_9,sensor_measurement_11,sensor_measurement_12,sensor_measurement_13,sensor_measurement_15,sensor_measurement_17,sensor_measurement_20,sensor_measurement_21
0,1,1,20.0072,0.7000,606.67,1481.04,1227.81,332.52,2323.67,8704.98,43.83,313.03,2387.78,9.2229,362,24.31,14.7007
1,1,2,24.9984,0.6200,536.22,1256.17,1031.48,174.46,1915.21,7999.94,36.11,163.61,2028.09,10.8632,306,14.36,8.5748
2,1,3,42.0000,0.8420,549.23,1340.13,1105.88,137.34,2211.93,8305.38,41.52,129.98,2387.95,9.3960,328,10.39,6.4365
3,1,4,42.0035,0.8402,549.19,1339.70,1107.26,137.23,2211.89,8301.00,41.73,129.48,2387.90,9.3594,328,10.56,6.2367
4,1,5,35.0079,0.8400,555.10,1353.04,1117.80,192.94,2222.71,8331.05,41.32,181.82,2387.87,9.3030,333,14.85,8.9326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41209,248,277,41.9991,0.8401,550.30,1364.40,1129.17,138.34,2212.35,8351.73,42.30,130.87,2388.50,9.4427,331,10.53,6.2620
41210,248,278,20.0026,0.7005,608.00,1494.75,1260.88,334.75,2324.23,8758.69,44.53,314.51,2388.33,9.2772,366,24.33,14.6486
41211,248,279,34.9988,0.8413,555.92,1370.65,1130.97,194.92,2223.57,8370.49,42.33,182.76,2388.64,9.3982,336,14.69,8.8389
41212,248,280,20.0027,0.7000,608.19,1489.11,1256.25,333.15,2324.19,8753.04,44.78,314.17,2388.37,9.2727,366,24.44,14.6887
41213,248,281,35.0075,0.8402,556.40,1378.58,1140.70,194.26,2223.50,8392.96,42.08,181.88,2388.59,9.3964,335,14.72,8.8502

RUL

In [13]:
df_RUL_1 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD001.txt', sep=" ", header=None)
df_RUL_2 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD002.txt', sep=" ", header=None)
df_RUL_3 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD003.txt', sep=" ", header=None)
df_RUL_4 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD004.txt', sep=" ", header=None)

In [14]:
list_df_rul = [df_RUL_1, df_RUL_2, df_RUL_3, df_RUL_4]

In [15]:
new_list_rul = []
for df in list_df_rul:
    df.dropna(axis=1,inplace=True)
    df.columns = ["RUL"]
    new_list_rul.append(df)

In [16]:
df_RUL_1 = new_list_rul[0]
df_RUL_2 = new_list_rul[1]
df_RUL_3 = new_list_rul[2]
df_RUL_4 = new_list_rul[3]

In [17]:
df_RUL_4

     RUL
0     22
1     39
2    107
3     75
4    149
..   ...
243   35
244  131
245  194
246  112
247   26

[248 rows x 1 columns]

#### Store the datasets

In [18]:
%store df_train_1
%store df_train_2
%store df_train_3
%store df_train_4

%store df_test_1
%store df_test_2
%store df_test_3
%store df_test_4

%store df_RUL_1
%store df_RUL_2
%store df_RUL_3
%store df_RUL_4

Stored 'df_train_1' (DataFrame)
Stored 'df_train_2' (DataFrame)
Stored 'df_train_3' (DataFrame)
Stored 'df_train_4' (DataFrame)
Stored 'df_test_1' (DataFrame)
Stored 'df_test_2' (DataFrame)
Stored 'df_test_3' (DataFrame)
Stored 'df_test_4' (DataFrame)
Stored 'df_RUL_1' (DataFrame)
Stored 'df_RUL_2' (DataFrame)
Stored 'df_RUL_3' (DataFrame)
Stored 'df_RUL_4' (DataFrame)

Merge SVR

In [18]:
nrows2 = df_train_2[df_train_2["ID"]==260].shape[0]
df_train_2.drop(df_train_2.tail(nrows2).index,inplace=True)
nrows4 = df_train_4[df_train_4["ID"]==249].shape[0]
df_train_4.drop(df_train_4.tail(nrows4).index,inplace=True)

In [19]:
l1 = len(df_train_1["ID"].unique())
l2 = len(df_train_2["ID"].unique())
l3 = len(df_train_3["ID"].unique())

In [20]:
df_train_2["ID"] = df_train_2["ID"] + l1
df_train_3["ID"] = df_train_3["ID"] + l1 + l2
df_train_4["ID"] = df_train_4["ID"] + l1 + l2 + l3

l1t = len(df_test_1["ID"].unique())
l2t = len(df_test_2["ID"].unique())
l3t = len(df_test_3["ID"].unique())

df_test_2["ID"] = df_test_2["ID"] + l1t
df_test_3["ID"] = df_test_3["ID"] + l1t + l2t
df_test_4["ID"] = df_test_4["ID"] + l1t + l2t + l3t

<ipython-input-20-bdff248d3627>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_2["ID"] = df_test_2["ID"] + l1t
<ipython-input-20-bdff248d3627>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_3["ID"] = df_test_3["ID"] + l1t + l2t
<ipython-input-20-bdff248d3627>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_4["ID"] = df_test_4["ID"] + l1t + l2t + l3t

In [21]:
df_trains = pd.concat([df_train_1, df_train_2, df_train_3, df_train_4])
df_tests = pd.concat([df_test_1, df_test_2, df_test_3, df_test_4])
df_ruls = pd.concat([df_RUL_1, df_RUL_2, df_RUL_3, df_RUL_4])

In [22]:
labels_to_drop = ["ID","Cycle"]
X_train = df_trains.drop(labels_to_drop+["RUL"], axis=1)
y_train = df_trains["RUL"]

X_test = df_tests.groupby("ID").last().reset_index().drop(labels_to_drop, axis=1)
y_test = df_ruls
print("X_train columns: ", X_train.columns, "\n",
     "X_test columns: ", X_test.columns, "\n",
     y_train.shape)

X_train columns:  Index(['operarional_setting_1', 'operarional_setting_2',
       'sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4',
       'sensor_measurement_7', 'sensor_measurement_8', 'sensor_measurement_9',
       'sensor_measurement_11', 'sensor_measurement_12',
       'sensor_measurement_13', 'sensor_measurement_15',
       'sensor_measurement_17', 'sensor_measurement_20',
       'sensor_measurement_21'],
      dtype='object')
 X_test columns:  Index(['operarional_setting_1', 'operarional_setting_2',
       'sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4',
       'sensor_measurement_7', 'sensor_measurement_8', 'sensor_measurement_9',
       'sensor_measurement_11', 'sensor_measurement_12',
       'sensor_measurement_13', 'sensor_measurement_15',
       'sensor_measurement_17', 'sensor_measurement_20',
       'sensor_measurement_21'],
      dtype='object')
 (159788,)

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVR
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import *

In [24]:
clips = np.arange(100,160,10).tolist()
train_scores = []
test_scores = []
for clip in clips:
    
    y_train_clip = df_trains["RUL"].clip(upper=clip)

    scaler = MinMaxScaler()
    scaler.fit(X_train)
    X_train_scal = scaler.transform(X_train)
    X_test_scal = scaler.transform(X_test)

    svr = SVR(kernel="linear")
    svr.fit(X_train_scal, y_train_clip)
    
    preds_train_svr = svr.predict(X_train_scal)
    r2_tr = r2_score(y_train_clip, preds_train)
    train_scores.append(r2_tr)
    print(" TRAIN SCORE WITH {} upper clipped RUL: ".format(clip), r2_score(y_train_clip, preds_train_svr))
    
    preds_test_svr = svr.predict(X_test_scal)
    r2_ts = r2_score(y_test, preds_test_svr)
    test_scores.append(r2_ts)
    print(" TEST SCORE WITH {} upper clipped RUL: ".format(clip), r2_score(y_test, preds_test_svr))

NameError: name 'preds_train' is not defined

In [ ]:
plt.plot(clips,train_scores,label="train scores")
plt.plot(clips, test_scores, label="test scores")
plt.legend()
mx_test = max(test_scores)
mx_idx = test_scores.index(mx_test)
train_mx_test = train_scores[mx_idx]
top_clip = clips[mx_idx]
print("Train Score from max Test Score: ", train_mx_test, "\n",
      "Max Test Score: ", mx_test, "\n",
     "Achieved with {} upper clipped RUL".format(top_clip))