Este script esta hecho para introducir todos los datasets train y test de los distintos archivos, es un repositorio a partir del cual otros scripts puedan extraer directamente la informacion y no sea necesario copiar todo el pifostio

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

TRAIN

In [31]:
df_train_1 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD001.txt', sep=" ", header=None)
df_train_2 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD002.txt', sep=" ", header=None)
df_train_3 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD003.txt', sep=" ", header=None)
df_train_4 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/train_FD004.txt', sep=" ", header=None)

In [32]:
list_df = [df_train_1, df_train_2, df_train_3, df_train_4]

In [33]:
list_units_1 = 3
operational_list = []
for n in range(1,list_units_1+1):
    operational = "operarional_setting_" + str(n)
    operational_list.append(operational)

list_units_2 = 23
sensor_measurement_list = []
for n in range(1,list_units_2+1):
    sensor = "sensor_measurement_" + str(n)
    sensor_measurement_list.append(sensor)

In [34]:
new_list = []
for df in list_df:
    
    df.columns = ["ID", "Cycle"] + operational_list + sensor_measurement_list

    df = df.dropna(axis=1)

    max_cycle_dataset_1 = df.groupby(["ID"])["Cycle"].max().reset_index()
    max_cycle_dataset_1 = max_cycle_dataset_1.rename(columns={"Cycle":"Max_cycle"})
    df = df.merge(max_cycle_dataset_1, how="inner", on="ID")
    df["RUL"] = df["Max_cycle"] - df["Cycle"]
    df = df.drop(["Max_cycle"],axis=1)

    #df.drop(columns="operarional_setting_3",axis=1, inplace=True)
    #columns_to_delete = ['sensor_measurement_1', 'sensor_measurement_5', 'sensor_measurement_6', 'sensor_measurement_10',"sensor_measurement_14", 'sensor_measurement_16', 'sensor_measurement_18', 'sensor_measurement_19']
    #df.drop(columns=columns_to_delete, axis=1, inplace=True)
    new_list.append(df)

In [35]:
df_train_1 = new_list[0]
df_train_2 = new_list[1]
df_train_3 = new_list[2]
df_train_4 = new_list[3]

In [36]:
df_train_3

,ID,Cycle,operarional_setting_1,operarional_setting_2,operarional_setting_3,sensor_measurement_1,sensor_measurement_2,sensor_measurement_3,sensor_measurement_4,sensor_measurement_5,...,sensor_measurement_13,sensor_measurement_14,sensor_measurement_15,sensor_measurement_16,sensor_measurement_17,sensor_measurement_18,sensor_measurement_19,sensor_measurement_20,sensor_measurement_21,RUL
0,1,1,-0.0005,0.0004,100.0,518.67,642.36,1583.23,1396.84,14.62,...,2388.01,8145.32,8.4246,0.03,391,2388,100.0,39.11,23.3537,258
1,1,2,0.0008,-0.0003,100.0,518.67,642.50,1584.69,1396.89,14.62,...,2388.03,8152.85,8.4403,0.03,392,2388,100.0,38.99,23.4491,257
2,1,3,-0.0014,-0.0002,100.0,518.67,642.18,1582.35,1405.61,14.62,...,2388.00,8150.17,8.3901,0.03,391,2388,100.0,38.85,23.3669,256
3,1,4,-0.0020,0.0001,100.0,518.67,642.92,1585.61,1392.27,14.62,...,2388.08,8146.56,8.3878,0.03,392,2388,100.0,38.96,23.2951,255
4,1,5,0.0016,0.0000,100.0,518.67,641.68,1588.63,1397.65,14.62,...,2388.03,8147.80,8.3869,0.03,392,2388,100.0,39.14,23.4583,254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24715,100,148,-0.0016,-0.0003,100.0,518.67,643.78,1596.01,1424.11,14.62,...,2388.30,8138.08,8.5036,0.03,394,2388,100.0,38.44,22.9631,4
24716,100,149,0.0034,-0.0003,100.0,518.67,643.29,1596.38,1429.14,14.62,...,2388.28,8144.36,8.5174,0.03,395,2388,100.0,38.50,22.9746,3
24717,100,150,-0.0016,0.0004,100.0,518.67,643.84,1604.53,1431.41,14.62,...,2388.24,8135.95,8.5223,0.03,396,2388,100.0,38.39,23.0682,2
24718,100,151,-0.0023,0.0004,100.0,518.67,643.94,1597.56,1426.57,14.62,...,2388.26,8141.24,8.5148,0.03,395,2388,100.0,38.31,23.0753,1
24719,100,152,0.0000,0.0003,100.0,518.67,643.64,1599.04,1436.06,14.62,...,2388.24,8136.98,8.5150,0.03,396,2388,100.0,38.56,23.0847,0

TEST

In [37]:
df_test_1 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD001.txt', sep=" ", header=None)
df_test_2 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD002.txt', sep=" ", header=None)
df_test_3 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD003.txt', sep=" ", header=None)
df_test_4 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/test_FD004.txt', sep=" ", header=None)

In [38]:
list_df_test = [df_test_1, df_test_2, df_test_3, df_test_4]

In [39]:
new_list_test = []
for df in list_df_test:
    
    df.columns = ["ID", "Cycle"] + operational_list + sensor_measurement_list
    df = df.dropna(axis=1)

    #df.drop(columns="operarional_setting_3",axis=1, inplace=True)
    #columns_to_delete = ['sensor_measurement_1', 'sensor_measurement_5', 'sensor_measurement_6', 'sensor_measurement_10',"sensor_measurement_14", 'sensor_measurement_16', 'sensor_measurement_18', 'sensor_measurement_19']
    #df.drop(columns=columns_to_delete, axis=1, inplace=True)
    new_list_test.append(df)

In [40]:
df_test_1 = new_list_test[0]
df_test_2 = new_list_test[1]
df_test_3 = new_list_test[2]
df_test_4 = new_list_test[3]

In [41]:
df_test_3

,ID,Cycle,operarional_setting_1,operarional_setting_2,operarional_setting_3,sensor_measurement_1,sensor_measurement_2,sensor_measurement_3,sensor_measurement_4,sensor_measurement_5,...,sensor_measurement_12,sensor_measurement_13,sensor_measurement_14,sensor_measurement_15,sensor_measurement_16,sensor_measurement_17,sensor_measurement_18,sensor_measurement_19,sensor_measurement_20,sensor_measurement_21
0,1,1,-0.0017,-0.0004,100.0,518.67,641.94,1581.93,1396.93,14.62,...,521.89,2387.94,8133.48,8.3760,0.03,391,2388,100.0,39.07,23.4468
1,1,2,0.0006,-0.0002,100.0,518.67,642.02,1584.86,1398.90,14.62,...,521.85,2388.01,8137.44,8.4062,0.03,391,2388,100.0,39.04,23.4807
2,1,3,0.0014,-0.0003,100.0,518.67,641.68,1581.78,1391.92,14.62,...,522.10,2387.94,8138.25,8.3553,0.03,391,2388,100.0,39.10,23.4244
3,1,4,0.0027,0.0001,100.0,518.67,642.20,1584.53,1395.34,14.62,...,522.45,2387.96,8137.07,8.3709,0.03,392,2388,100.0,38.97,23.4782
4,1,5,-0.0001,0.0001,100.0,518.67,642.46,1589.03,1395.86,14.62,...,521.91,2387.97,8134.20,8.4146,0.03,391,2388,100.0,39.09,23.3950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16591,100,243,0.0011,-0.0003,100.0,518.67,643.04,1594.99,1411.28,14.62,...,529.23,2388.24,8162.24,8.2939,0.03,395,2388,100.0,39.40,23.4949
16592,100,244,-0.0024,0.0002,100.0,518.67,642.47,1591.27,1417.64,14.62,...,529.27,2388.26,8163.24,8.3247,0.03,394,2388,100.0,39.42,23.6011
16593,100,245,-0.0053,0.0002,100.0,518.67,642.70,1593.81,1412.70,14.62,...,529.48,2388.28,8162.12,8.3264,0.03,394,2388,100.0,39.43,23.5482
16594,100,246,-0.0006,0.0001,100.0,518.67,642.19,1595.63,1406.58,14.62,...,529.39,2388.33,8164.20,8.2908,0.03,395,2388,100.0,39.40,23.6687
16595,100,247,0.0023,0.0004,100.0,518.67,643.19,1592.54,1407.20,14.62,...,529.59,2388.29,8169.24,8.3191,0.03,392,2388,100.0,39.41,23.6536

RUL

In [42]:
df_RUL_1 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD001.txt', sep=" ", header=None)
df_RUL_2 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD002.txt', sep=" ", header=None)
df_RUL_3 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD003.txt', sep=" ", header=None)
df_RUL_4 = pd.read_csv('/home/dsc/Downloads/CMAPSSData/RUL_FD004.txt', sep=" ", header=None)

In [43]:
list_df_rul = [df_RUL_1, df_RUL_2, df_RUL_3, df_RUL_4]

In [44]:
new_list_rul = []
for df in list_df_rul:
    df.dropna(axis=1,inplace=True)
    df.columns = ["RUL"]
    new_list_rul.append(df)

In [45]:
df_RUL_1 = new_list_rul[0]
df_RUL_2 = new_list_rul[1]
df_RUL_3 = new_list_rul[2]
df_RUL_4 = new_list_rul[3]

In [46]:
df_RUL_4

     RUL
0     22
1     39
2    107
3     75
4    149
..   ...
243   35
244  131
245  194
246  112
247   26

[248 rows x 1 columns]

#### Store the datasets

In [47]:
%store df_train_1
%store df_train_2
%store df_train_3
%store df_train_4

%store df_test_1
%store df_test_2
%store df_test_3
%store df_test_4

%store df_RUL_1
%store df_RUL_2
%store df_RUL_3
%store df_RUL_4

Stored 'df_train_1' (DataFrame)
Stored 'df_train_2' (DataFrame)
Stored 'df_train_3' (DataFrame)
Stored 'df_train_4' (DataFrame)
Stored 'df_test_1' (DataFrame)
Stored 'df_test_2' (DataFrame)
Stored 'df_test_3' (DataFrame)
Stored 'df_test_4' (DataFrame)
Stored 'df_RUL_1' (DataFrame)
Stored 'df_RUL_2' (DataFrame)
Stored 'df_RUL_3' (DataFrame)
Stored 'df_RUL_4' (DataFrame)

Merge SVR

In [18]:
nrows2 = df_train_2[df_train_2["ID"]==260].shape[0]
df_train_2.drop(df_train_2.tail(nrows2).index,inplace=True)
nrows4 = df_train_4[df_train_4["ID"]==249].shape[0]
df_train_4.drop(df_train_4.tail(nrows4).index,inplace=True)

In [19]:
l1 = len(df_train_1["ID"].unique())
l2 = len(df_train_2["ID"].unique())
l3 = len(df_train_3["ID"].unique())

In [20]:
df_train_2["ID"] = df_train_2["ID"] + l1
df_train_3["ID"] = df_train_3["ID"] + l1 + l2
df_train_4["ID"] = df_train_4["ID"] + l1 + l2 + l3

l1t = len(df_test_1["ID"].unique())
l2t = len(df_test_2["ID"].unique())
l3t = len(df_test_3["ID"].unique())

df_test_2["ID"] = df_test_2["ID"] + l1t
df_test_3["ID"] = df_test_3["ID"] + l1t + l2t
df_test_4["ID"] = df_test_4["ID"] + l1t + l2t + l3t

<ipython-input-20-bdff248d3627>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_2["ID"] = df_test_2["ID"] + l1t
<ipython-input-20-bdff248d3627>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_3["ID"] = df_test_3["ID"] + l1t + l2t
<ipython-input-20-bdff248d3627>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_4["ID"] = df_test_4["ID"] + l1t + l2t + l3t

In [21]:
df_trains = pd.concat([df_train_1, df_train_2, df_train_3, df_train_4])
df_tests = pd.concat([df_test_1, df_test_2, df_test_3, df_test_4])
df_ruls = pd.concat([df_RUL_1, df_RUL_2, df_RUL_3, df_RUL_4])

In [22]:
labels_to_drop = ["ID","Cycle"]
X_train = df_trains.drop(labels_to_drop+["RUL"], axis=1)
y_train = df_trains["RUL"]

X_test = df_tests.groupby("ID").last().reset_index().drop(labels_to_drop, axis=1)
y_test = df_ruls
print("X_train columns: ", X_train.columns, "\n",
     "X_test columns: ", X_test.columns, "\n",
     y_train.shape)

X_train columns:  Index(['operarional_setting_1', 'operarional_setting_2',
       'sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4',
       'sensor_measurement_7', 'sensor_measurement_8', 'sensor_measurement_9',
       'sensor_measurement_11', 'sensor_measurement_12',
       'sensor_measurement_13', 'sensor_measurement_15',
       'sensor_measurement_17', 'sensor_measurement_20',
       'sensor_measurement_21'],
      dtype='object')
 X_test columns:  Index(['operarional_setting_1', 'operarional_setting_2',
       'sensor_measurement_2', 'sensor_measurement_3', 'sensor_measurement_4',
       'sensor_measurement_7', 'sensor_measurement_8', 'sensor_measurement_9',
       'sensor_measurement_11', 'sensor_measurement_12',
       'sensor_measurement_13', 'sensor_measurement_15',
       'sensor_measurement_17', 'sensor_measurement_20',
       'sensor_measurement_21'],
      dtype='object')
 (159788,)